apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- behavior: merge
  files:
  - kleat/clouddriver.yml
  name: clouddriver-config
- behavior: merge
  files:
  - kleat/settings.js
  name: deck-config
- behavior: merge
  files:
  - kleat/echo.yml
  name: echo-config
- behavior: merge
  files:
  - kleat/fiat.yml
  name: fiat-config
- behavior: merge
  files:
  - kleat/front50.yml
  name: front50-config
- behavior: merge
  files:
  - kleat/gate.yml
  name: gate-config
- behavior: merge
  files:
  - kleat/igor.yml
  name: igor-config
- behavior: merge
  files:
  - kleat/kayenta.yml
  name: kayenta-config
- behavior: merge
  files:
  - kleat/orca.yml
  name: orca-config
- behavior: merge
  files:
  - kleat/rosco.yml
  name: rosco-config
- behavior: merge
  name: spinnaker-monitoring-config
  files:
  - kleat/spinnaker-monitoring.yml
- behavior: merge
  name: spinnaker-monitoring-filters
  files: []
- behavior: merge
  name: spinnaker-secrets
  files: []
configMapGenerator:
- behavior: merge
  name: deck-env
  envs:
  - kleat/deck.env
resources:
- github.com/spinnaker/kustomization-base/core?ref=master
# - github.com/spinnaker/kustomization-base/kayenta?ref=master
# - github.com/spinnaker/kustomization-base/fiat?ref=master
commonLabels:
  app.kubernetes.io/component: server
  app.kubernetes.io/managed-by: kleat
  app.kubernetes.io/part-of: spinnaker
  app.kubernetes.io/version: spinnaker-master-latest-validated
namespace: spinnaker
images:
- name: us-docker.pkg.dev/spinnaker-community/docker/clouddriver
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/deck
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/echo
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/fiat
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/front50
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/gate
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/igor
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/kayenta
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/monitoring-daemon
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/orca
  newTag: spinnaker-master-latest-validated
- name: us-docker.pkg.dev/spinnaker-community/docker/rosco
  newTag: spinnaker-master-latest-validated
