apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- behavior: merge
  files:
  - kleat/clouddriver.yml
  name: clouddriver-config
- behavior: merge
  files:
  - kleat/echo.yml
  name: echo-config
- behavior: merge
  files:
  - kleat/fiat.yml
  name: fiat-config
- behavior: merge
  files:
  - kleat/front50.yml
  name: front50-config
- behavior: merge
  files:
  - kleat/gate.yml
  name: gate-config
- behavior: merge
  files:
  - kleat/igor.yml
  name: igor-config
- behavior: merge
  files:
  - kleat/orca.yml
  name: orca-config
- behavior: merge
  name: spinnaker-secrets
resources:
- github.com/spinnaker/kustomization-base/base
