apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate
spec:
  template:
    spec:
      containers:
        - name: gate
          readinessProbe:
            $patch: replace
            exec:
              command:
              - wget
              - --no-check-certificate
              - --spider
              - -q
              - http://localhost:8084/health
